---
- name: Fortinet Fortigate Global settings
  hosts: all
  connection: httpapi
  gather_facts: false
  vars:
   ansible_httpapi_use_ssl: true
   ansible_httpapi_validate_certs: false # set to yes for security
   ansible_httpapi_port: 443
  tasks:
   - name: Collect Fortigate facts
     register: system_status_output
     fortinet.fortios.fortios_monitor_fact:
      selector: 'system_status'

   - name: Collect Fortigate global config facts before possible changes
     register: system_global_facts_before
     fortinet.fortios.fortios_configuration_fact:
      selector: 'system_global'

   - name: Parse Fortigate version
     ansible.builtin.set_fact:
      fortigate_version: "{{ system_status_output.meta.version[1:] }}" # strip 'v' from the version number

   - name: Fortigate global config
     register: results_all
     fortinet.fortios.fortios_system_global:
      system_global:
       alias: "{{ inventory_hostname }}"
       gui_date_format: "yyyy/MM/dd"
       hostname: "{{ inventory_hostname }}"
       vdom_mode: "multi-vdom"

   - name: Fortigate global config version > 7.4.2
     register: results_above_742
     when: fortigate_version is version("7.4.2", '>')
     fortinet.fortios.fortios_system_global:
      system_global:
       timezone: "Europe/Amsterdam"

   - name: Fortigate global config version < 7.4.2
     register: results_below_742
     when: fortigate_version is version("7.4.2", '<')
     fortinet.fortios.fortios_system_global:
      system_global:
       timezone: "26"

   - name: Collect Fortigate global config facts after possible changes
     register: system_global_facts_after
     fortinet.fortios.fortios_configuration_fact:
      selector: 'system_global'

   - name: Show diff
     when: results_all.changed or results_below_742.changed or results_above_742.changed
     ansible.utils.fact_diff:
      before: "{{ system_global_facts_before }}"
      after: "{{ system_global_facts_after }}"
