---
- name: Fortinet Fortigate gather Interface-info
  hosts: all
  connection: httpapi
  gather_facts: false
  collections:
    - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
  tasks:
    - name: Collect Fortigate VDOM's
      fortios_configuration_fact:
        selector: 'system_vdom'
      register: system_vdom_output
    - name: Print Fortigate VDOM's
      debug:
        msg: "{{ system_vdom_output.meta.results }}"
    
    - name: Collect Fortigate vdom interfaces
      fortios_monitor_fact:
        vdom: "{{ item.name }}"
        selector: 'system_available-interfaces'
        params:
          include_vlan: true
          include_aggregate: true
      loop: "{{ system_vdom_output.meta.results }}"
      loop_control:
        label: "{{ item.name }}"
      register: system_interface_output
    - name: Print Fortigate interface output
      debug:
        msg: "{{ system_interface_output }}"