---
- name: Fortinet Fortigate hardening
  hosts: all
  connection: httpapi
  gather_facts: false
  collections:
   - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no # set to yes for security
    ansible_httpapi_port: 443
  tasks:
    - name: Collect Fortigate facts
      fortios_monitor_fact:
        selector: 'system_status'
      register: system_status_output
    
    - name: Parse Fortigate version
      set_fact:
        fortigate_version: "{{ system_status_output.meta.version[1:] }}" # strip 'v' from the version number
    
    - name: Fortigate global config hardening
      fortios_system_global:
        system_global:
          alias: "{{ inventory_hostname }}"
          gui_date_format: "yyyy/MM/dd"
          hostname: "{{ inventory_hostname }}"
          #timezone: "26"
          vdom_mode: "multi-vdom"
      register: results

    - name: Show diff
      when: results.changed
      ansible.utils.fact_diff:
        before: "{{ results.before }}"
        after: "{{ results.after }}"
          