---
- name: Fortinet Fortigate gather HA-info
  hosts: all
  connection: httpapi
  gather_facts: false
  collections:
   - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Collect Fortigate facts
      fortios_monitor_fact:
        selector: 'system_ha-statistics'
      register: system_status_output
    - name: Parse Fortigate version
      debug:
        msg: "{{ system_status_output }}"
    
