---
- name: Fortinet Fortigate Global settings
  hosts: all
  connection: httpapi
  gather_facts: false
  collections:
   - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false # set to yes for security
    ansible_httpapi_port: 443
  tasks:
    - name: Collect Fortigate facts
      fortios_monitor_fact:
        selector: 'system_status'
      register: system_status_output
    
    - name: Collect Fortigate global config facts before possible changes
      fortios_configuration_fact:
        selector: 'system_global'
      register: system_global_facts_before
    
    - name: Parse Fortigate version
      set_fact:
        fortigate_version: "{{ system_status_output.meta.version[1:] }}" # strip 'v' from the version number
    
    - name: Fortigate global config
      fortios_system_global:
        system_global:
          alias: "{{ inventory_hostname }}"
          gui_date_format: "yyyy/MM/dd"
          hostname: "{{ inventory_hostname }}"
          vdom_mode: "multi-vdom"
      register: results

    - name: Fortigate global config version > 7.4.2
      fortios_system_global:
        system_global:
          #timezone: "Europe/Amsterdam"
      register: results
      when: fortigate_version is version("7.4.2",'>')

    - name: Fortigate global config version < 7.4.2
      fortios_system_global:
        system_global:
          timezone: "26"
      register: results
      when: fortigate_version is version("7.4.2",'<')

    - name: Collect Fortigate global config facts after possible changes
      fortios_configuration_fact:
        selector: 'system_global'
      register: system_global_facts_after

    - name: Show diff
      when: results.changed
      ansible.utils.fact_diff:
        before: "{{ system_global_facts_before }}"
        after: "{{ system_global_facts_after }}"
          