---
- name: Configure VLANs on Cisco IOS Switch
  hosts: all
  collections:
   - cisco.ios
  gather_facts: no
  tasks:
    - include_vars:
        file: "{{ inventory_hostname }}_ports.yaml"
        name: port_list
    - debug:
        msg: "{{ port_list['ports'] }}"
    - name: Configure L2 Ports
      ios_l2_interfaces:
        config: "{{ port_list['ports'] }}"
        state: replaced
      when: ansible_network_os == 'cisco.ios.ios'
      register: results

    - name: Show diff
      when: results.changed
      ansible.utils.fact_diff:
        before: "{{ results.before }}"
        after: "{{ results.after }}"