---
- name: Configure VLANs on Cisco IOS Switch
  hosts: all
  collections:
   - cisco.ios
  gather_facts: false
  tasks:
    - name: Include vars file
      include_vars:
        file: vlan_list.yaml
        name: vlan_list
    - name: Create VLAN's
      cisco.ios.ios_vlans:
        config: "{{ vlan_list.vlans }}"
        state: replaced
      when: ansible_network_os == 'cisco.ios.ios'
      register: results

    - name: Show diff
      when: results.changed
      ansible.utils.fact_diff:
        before: "{{ results.before }}"
        after: "{{ results.after }}"