---
- name: Gather all facts from cisco network equipment
  hosts: all
  gather_facts:false
  tasks:
    - name: Gather IOS facts
      when: ansible_network_os == 'cisco.ios.ios'
      register: ios_facts
      cisco.ios.ios_facts:
        gather_subset:
          - all

    - name: Display facts
      ansible.builtin.debug:
        var: ios_facts

    - name: Gather resource facts
      register: ios_resource_facts
      cisco.ios.ios:
        gather_network_resources:
          - all

    - name: Display resource facts
      ansible.builtin.debug:
        var: ios_resource_facts
